#!/usr/bin/env python3
"""
SMP Version Bumper — updates version everywhere it matters.
Usage: python3 tools/bump_version.py V6.5
"""
import sys, json, os, re, glob

GRN = "\033[92m"; YEL = "\033[93m"; RED = "\033[91m"; RST = "\033[0m"
def _ok(msg):   print(f"  {GRN}[✓]{RST} {msg}")
def _warn(msg): print(f"  {YEL}[!]{RST} {msg}")
def _err(msg):  print(f"  {RED}[✗]{RST} {msg}")

def _replace_in_file(path, old_pattern, replacement, description=""):
    if not os.path.exists(path):
        _warn(f"File not found: {path}"); return False
    with open(path, "r", encoding="utf-8") as f: content = f.read()
    new_content, n = re.subn(old_pattern, replacement, content)
    if n == 0: _warn(f"Pattern not found in {os.path.basename(path)}: {description}"); return False
    with open(path, "w", encoding="utf-8") as f: f.write(new_content)
    _ok(f"{os.path.basename(path)} — {n} replacement(s) [{description}]"); return True

def main():
    if len(sys.argv) < 2:
        print("Usage: python3 bump_version.py <NEW_VERSION>")
        print("Example: python3 bump_version.py V5.2"); sys.exit(1)

    new_version = sys.argv[1].strip()
    if new_version.lower().startswith("v") and not new_version.startswith("V"):
        new_version = "V" + new_version[1:]
    ver_num = new_version.lstrip("vV")
    root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))

    print(f"\n{'═'*55}\n  SMP Version Bump → {new_version}\n{'═'*55}\n")

    # 1. config/metadata.json
    meta_path = os.path.join(root, "config", "metadata.json")
    if os.path.exists(meta_path):
        with open(meta_path, "r") as f: data = json.load(f)
        old_v = data.get("version", "?")
        data["version"] = new_version
        with open(meta_path, "w") as f: json.dump(data, f, indent=4)
        _ok(f"config/metadata.json  {old_v} → {new_version}")
    else:
        _err("config/metadata.json not found — creating it")
        os.makedirs(os.path.join(root, "config"), exist_ok=True)
        with open(meta_path, "w") as f: json.dump({"version": new_version}, f, indent=4)

    # 2. README.md & USER_GUIDE.md
    for doc_name in ("README.md", "USER_GUIDE.md"):
        doc = os.path.join(root, doc_name)
        if not os.path.exists(doc): _warn(f"{doc_name} not found"); continue
        with open(doc, "r", encoding="utf-8") as f: content = f.read()
        new_content = re.sub(r'([vV])\d+\.\d+(?:\.\d+)?', lambda m: m.group(1) + ver_num, content)
        new_content = re.sub(r'version-\d+\.\d+(?:\.\d+)?', f'version-{ver_num}', new_content)
        with open(doc, "w", encoding="utf-8") as f: f.write(new_content)
        _ok(doc_name)

    # 3. tools/report_generator.py — Generated By line
    rg = os.path.join(root, "tools", "report_generator.py")
    _replace_in_file(rg, r'Security Management Platform \(SMP\) V[\d.]+ Stable',
        f'Security Management Platform (SMP) {new_version} Stable', "Generated By label")

    # 4. ui/views/dashboard_layout.py — sidebar version label
    dl = os.path.join(root, "ui", "views", "dashboard_layout.py")
    _replace_in_file(dl, r"getattr\(self,\s*'version',\s*'V[\d.]+'\)",
        f"getattr(self, 'version', '{new_version}')", "version fallback label")

    # 5. ui/dashboard.py — fallback version string
    dash = os.path.join(root, "ui", "dashboard.py")
    _replace_in_file(dash, r'version\s*=\s*"V[\d.]+"', f'version = "{new_version}"', "version fallback")

    # 6. ui/views/splash_screen.py
    splash = os.path.join(root, "ui", "views", "splash_screen.py")
    _replace_in_file(splash, r'version\s*=\s*"V[\d.]+"', f'version = "{new_version}"', "splash fallback")
    _replace_in_file(splash, r'metadata\.get\("version",\s*"V[\d.]+"\)',
        f'metadata.get("version", "{new_version}")', "metadata fallback")

    # 7. main.py
    main_py = os.path.join(root, "main.py")
    _replace_in_file(main_py, r'V[\d.]+ Stable', f'{new_version} Stable', "main.py version string")

    # 8. Any remaining SMP version strings in other .py files
    patched_extra = 0
    for py_file in glob.glob(os.path.join(root, "**", "*.py"), recursive=True):
        if "__pycache__" in py_file: continue
        if py_file in (rg, dl, dash, splash, main_py): continue
        with open(py_file, "r", encoding="utf-8", errors="ignore") as f: content = f.read()
        new_content, n = re.subn(
            r'(["\'][^"\']*?(?:SMP|Security Management Platform)[^"\']*?V)\d+\.\d+(?:\.\d+)?',
            lambda m: m.group(1) + ver_num, content)
        if n > 0:
            with open(py_file, "w", encoding="utf-8") as f: f.write(new_content)
            _ok(f"{os.path.relpath(py_file, root)} — {n} inline version(s)")
            patched_extra += n

    print(f"\n{'═'*55}\n  {GRN}✅ Version bumped to {new_version}!{RST}\n{'═'*55}\n")

if __name__ == "__main__":
    main()
